apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uk8s-istio
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istio-base
    targetRevision: 1.23.1 # Adjust to the version you need
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uk8s-istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.23.1
    helm:
      parameters:
        - name: global.hub
          value: "docker.io/istio"
        - name: global.tag
          value: "1.23.1"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

