apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ck8s-metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://10.193.15.222:6443
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.8
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
