apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uk8s-istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: base
    helm:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.23.3
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
