apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uk8s-metricsserver
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    helm:
      parameters:
      - name: hostNetwork.enabled
        value: "true"
      - name: containerPort
        value: "10251"
      values: |
        parameters:
        defaultArgs:
          - --cert-dir=/tmp
          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
          - --kubelet-use-node-status-port
          - --metric-resolution=15s
          - --kubelet-insecure-tls
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
