apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bk8s-ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    name: bk8s
  project: default
  source:
    chart: ingress-nginx
    helm:
      parameters:
      - name: hostNetwork.enabled
        value: "true"
      - name: containerPort
        value: "10254"
      - name: controller.service.type
        value: LoadBalancer
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.9.1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
      ServerSideApply=true
