apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bk8s-longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true ServerSideApply=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.1 
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
  destination:
    name: bk8s
    namespace: longhorn-system

